# Generated by Django 4.2 on 2023-06-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_email_address_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.AddField(
            model_name='postdetails',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postdetails',
            name='tags',
            field=models.ManyToManyField(to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='postdetails',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='postdetails',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='postdetails',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
