# Generated by Django 4.2 on 2023-06-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_tag_post_postdetails_image_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='postdetails',
            options={'verbose_name_plural': 'Postdetails'},
        ),
        migrations.AlterField(
            model_name='postdetails',
            name='image_name',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
